/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        outline: "#6e7b6c",
        "on-tertiary-container": "#fffbff",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#314d3e",
        "inverse-surface": "#2e3132",
        secondary: "#486554",
        surface: "#f8f9fa",
        "on-tertiary-fixed-variant": "#8a143c",
        background: "#f8f9fa",
        "surface-tint": "#006e2d",
        "secondary-fixed-dim": "#afceba",
        "primary-fixed-dim": "#62df7d",
        "inverse-on-surface": "#f0f1f2",
        "secondary-container": "#caead6",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#042014",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffd9de",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#caead6",
        "on-error-container": "#93000a",
        "on-secondary-container": "#4e6b5a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005320",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#62df7d",
        "surface-dim": "#d9dadb",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        tertiary: "#7ffc97",
        "tertiary-container": "#c74668",
        "on-background": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "outline-variant": "#bdcaba",
        "on-surface-variant": "#3e4a3d",
        "on-primary-fixed": "#002109",
        "tertiary-fixed-dim": "#ffb2bf",
        primary: "#006b2c",
        "on-primary-container": "#f7fff2",
        "surface-container-low": "#f3f4f5",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#3f0016",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#7ffc97",
        "primary-container": "#00873a",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
